pwm: pwm-adp5585: fix get_state callback prototype
Since [1] the .get_state() callback returns an error code.
Modify the pwm_adp5585_get_state() accordingly. This fixes the
building error [2].

[1]
commit 547cc8dae2474 ("pwm: Make .get_state() callback return an error code")

[2]
drivers/pwm/pwm-adp5585.c:170:22: error: initialization of ‘int (*)(struct pwm_chip *, struct pwm_device *, struct pwm_state *)’ from incompatible pointer type ‘void (*)(struct pwm_chip *, struct pwm_device *, struct pwm_state *)’ [-Werror=incompatible-pointer-types]
  170 |         .get_state = pwm_adp5585_get_state,
      |                      ^~~~~~~~~~~~~~~~~~~~~
drivers/pwm/pwm-adp5585.c:170:22: note: (near initialization for ‘adp5585_pwm_ops.get_state’)

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>