thermal: imx: fix a merging issue
The imx_thermal_data data should be provided in imx_get_trend()
to use it in pm_runtime_put(data->dev) command introduced with
merging from stable kernel version.
This fixes the building error [1].

[1]
drivers/thermal/imx_thermal.c: In function 'imx_get_trend':
drivers/thermal/imx_thermal.c:407:17: error: 'data' undeclared (first use in this function); did you mean '_data'?

Fixes: 13f64bbe4255 ("thermal/drivers/imx: Implement runtime PM support")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>