Revert "net: stmmac: fix FPE events losing"
This reverts commit ed7e211b67863546afea3a2ed5164e41d00e8160.

This fixes the following build error:

drivers/net/ethernet/freescale/fec_uio.c: In function ‘stmmac_fpe_link_state_handle’:
drivers/net/ethernet/freescale/../stmicro/stmmac/hwif.h:15:17: error: too few arguments to function ‘priv->hw->mac->fpe_send_mpacket’
   15 |                 (__priv)->hw->__module->__cname((__arg0), ##__args); \
      |                 ^
drivers/net/ethernet/freescale/../stmicro/stmmac/hwif.h:502:9: note: in expansion of macro ‘stmmac_do_void_callback’
  502 |         stmmac_do_void_callback(__priv, mac, fpe_send_mpacket, __args)
      |         ^~~~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/freescale/fec_uio.c:266:17: note: in expansion of macro ‘stmmac_fpe_send_mpacket’
  266 |                 stmmac_fpe_send_mpacket(priv, priv->ioaddr, MPACKET_VERIFY);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>